version: "3.9"

services:
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - "27017:27017"

  app:
    build: .
    image: mlfalconaro/portfolio-reflex:${TAG:-latest}
    ports:
      - "3000:3000"
      - "8000:8000"
    environment:
      MONGO_USER: admin
      MONGO_PASSWORD: secret
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: portfolio_db
    depends_on:
      - mongo
