name: Build, Test, and Push Docker Image

on:
  push:
    branches: [11_cicd, main]
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Extract Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mlfalconaro/portfolio-reflex
          tags: |
            type=semver,pattern={{version}}

      - name: Build Docker image
        run: |
          docker build -t mlfalconaro/portfolio-reflex:latest .

      - name: Show build info
        run: |
          echo "✅ Build completed!"

  test:
    name: Test Docker Image
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images with Docker Compose
        run: |
          TAG=latest docker compose build --no-cache

      - name: Run services with Docker Compose
        run: |
          TAG=latest docker compose up -d
          echo "Waiting for MongoDB..."
          docker compose exec app sh -c '
            until nc -z mongo 27017; do
              echo "MongoDB not ready yet..."
              sleep 2
            done
            echo "MongoDB ready!"
          '

      - name: Run tests
        run: |
          docker compose exec -T app pytest -vv --maxfail=1 --disable-warnings

      - name: Tear down
        if: always()
        run: docker compose down

  push:
    name: Push Docker Image to DockerHub
    runs-on: ubuntu-latest
    needs: test
    if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract Docker tags
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: mlfalconaro/portfolio-reflex
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Show results
        run: |
          echo "✅ Docker image pushed to DockerHub!"
          echo "Tag: ${{ github.ref }}"
